### ISSUE TITLE
关于翻译句子时的特性

### ISSUE THREAD

**Issue by RealAidanJoe** [yaobinbin333/bob-plugin-cambridge-dictionary#1]
请问一下可以增加一个特性就是当翻译句子或者找不到的时候不展开词条吗？
就是类似金山词霸这种，如果是在翻译句子的时候不展开
![image](https://user-images.githubusercontent.com/71580066/226107853-1746fc62-8528-4029-b893-b51e16502d77.png)

**Comment by yaobinbin333** [comment]
新版本有这个功能的，可以去偏好设置-->插件列表-->右键我的插件检查更新，如果因为网络问题没下载，可以去releases中下载最新版本安装一下，链接如下：
https://github.com/yaobinbin333/bob-plugin-cambridge-dictionary/releases

**Comment by RealAidanJoe** [comment]
感谢！有用！
